import { UniSubject } from './../models/data.model';
import { Tutor } from "../models/data.model";
export module Data {
    export const tutorData = [
        new Tutor(0, 'Michael', 60),
        new Tutor(13, 'Jiaha', 65),
        new Tutor(35, 'Joel', 80),
        new Tutor(14, 'Xiaoji', 70),
        new Tutor(1, 'Heat', 60),
        new Tutor(28, 'Ji', 75),
        new Tutor(29, 'Troy', 75),
        new Tutor(30, 'Yuya', 55),
        new Tutor(2, 'Qing', 60),
        new Tutor(31, 'Imran', 75),
        new Tutor(34, 'Yind', 80),
        new Tutor(32, 'Xuanhu', 75),
        new Tutor(33, 'Yu', 80),
        new Tutor(4, 'Ari', 60),
        new Tutor(36, 'Loui', 80),
        new Tutor(3, 'Jaso', 60),
        new Tutor(5, 'Gar', 55),
        new Tutor(6, 'Matthew', 65),
        new Tutor(7, 'Laura', 65),
        new Tutor(8, 'Nonie', 55),
        new Tutor(9, 'Liyua', 55),
        new Tutor(10, 'Hai', 55),
        new Tutor(11, 'Jack', 65),
        new Tutor(12, 'Vincen', 65),
        new Tutor(15, 'Kiera', 70),
        new Tutor(16, 'Andrew', 70),
        new Tutor(17, 'Charlie', 70),
        new Tutor(18, 'Isabell', 70),
        new Tutor(19, 'Rya', 70),
        new Tutor(20, 'James', 70),
        new Tutor(21, 'Emil', 70),
        new Tutor(22, 'Rebecc', 70),
        new Tutor(23, 'Danie', 70),
        new Tutor(24, 'Mathew', 70),
        new Tutor(25, 'Nicholas', 75),
        new Tutor(26, 'Jami', 75),
        new Tutor(27, 'Mihai', 75),
        new Tutor(37, 'Jason', 80),
        new Tutor(39, 'Samuel', 80),
        new Tutor(40, 'Joh', 80),
    ]
    
    export const subjectData = [
        new UniSubject('USYD', 'COMP2017'),
        new UniSubject('USYD', 'INFO2120'),
        new UniSubject('USYD', 'INFO2820'),
        new UniSubject('USYD', 'INFO1105'),
        new UniSubject('USYD', 'INFO1905'),
        new UniSubject('USYD', 'COMP2129'),
        new UniSubject('USYD', 'COMP2007'),
        new UniSubject('USYD', 'COMP2907'),
        new UniSubject('USYD', 'INFO1903'),
        new UniSubject('USYD', 'INFO2315'),
        new UniSubject('USYD', 'MATH1001'),
        new UniSubject('USYD', 'INFO3504'),
        new UniSubject('USYD', 'MATH2069'),
        new UniSubject('USYD', 'MATH2068'),
        new UniSubject('USYD', 'MATH2061'),
        new UniSubject('USYD', 'MATH3066'),
        new UniSubject('USYD', 'MATH3076'),
        new UniSubject('USYD', 'MATH3068'),
        new UniSubject('USYD', 'INFO3600'),
    ]

}
